#!/bin/bash
outFile="/home/willy/LateX/BA/Results/AdvancedvsSimple/Simulations/introductoryExample"

PA="/home/willy/workspace/RNAMv2/Implementation"

params="$PA/./RNAM --readParametersFromFile 1 --exportParametersToFile 1 --randomSeed 3313 --simulation 1 --maxBatches 30"

call()
{
    out=$1
    name=$2
    parametersToAdd=$3
    dire="$out/$name"

    mkdir -p $dire
    cp -u $outFile/parametersCopy $dire/parameters
    ca="$params --pathToParameters $dire/parameters --readFilesIn $dire --outFileNamePrefix $dire $parametersToAdd"
    $ca

}

test()
{
    cost=$1
    pseudoCount=$2
    lambda=$3

    direct="$outFile/co$1_ps$2_la$3"
    mkdir -p $direct

    call $direct random "--estimator 0 --cost $cost --pseudoCount $pseudoCount --lambda $lambda"

    call $direct simple "--estimator 1 --cost $cost --pseudoCount $pseudoCount --lambda $lambda"

    call $direct advanced "--estimator 2 --cost $cost --pseudoCount $pseudoCount --lambda $lambda"

    RC="Rscript --vanilla /home/willy/Bachelorarbeit/Manager/Rvisualization/visOverview.R $direct/ random simple advanced"
    $RC
}

costs=(0.0)
pseudos=(0.0 1.0)
lambdas=(0.0 0.1 1.0 100.0 1000000)


for c in "${costs[@]}"
do
    for p in "${pseudos[@]}"
    do
        for l in "${lambdas[@]}"
        do
            test $c $p $l &
        done
    done
done
wait

